### PR TITLE
Update to 1.19.2

### PR DESCRIPTION
**Pull request by solonovamax**
Updates the mod to 1.19.2

I haven't tested if this works on 1.19.3 or 1.19.4, however I will be soon updating this mod to 1.19.4, as soon as I update my server.

### CODE REVIEW

**Comment by asoji** [comment]
Thank you for the PR! I think this looks good, but if I may ask, why is the 1/10 chance for normal creepers removed?

**Comment by solonovamax** [comment]
ah, I removed it because I personally didn't want it on my server. I updated the mod a while ago, and I forgot about that change when I PR'd.

Alternatively, I can introduce a config file that allows you to enable/disable/make it  rarer.

**Comment by asoji** [comment]
Ah, I see. IMO a config should be added for that, but only if you want. I just think it should stay since it was vanilla behavior.

**Comment by solonovamax** [comment]
wdym? since when was a 10% chance to drop the head vanilla behaviour?

**Comment by Cart3r1234** [comment]
It was a feature that was removed shortly after being added.  If I'm not mistaken, it only happened for a snapshot or two.

**Comment by asoji** [comment]
I'm just going to merge this. Seems good enough, we can worry about the 10% thing later, maybe as a config option or something.

**Pull request merged**
